### PR TITLE
Fix failing tests

### LINKED ISSUE #70: Tests are sometimes failing
```
16:02:46.682 [info]  Protocol 'inet_tcp': register/listen error: econnrefused


16:02:46.686 [info]  Trying to start epmd...


  1) test cnode without interface (ExampleTest)
     test/example_test.exs:28
     ** (EXIT from #PID<0.607.0>) shutdown

.....

Finished in 0.2 seconds
6 tests, 1 failure

Randomized with seed 576421


  1) test Example test project (Bundlex.IntegrationTest)
     test/bundlex/integration_test.exs:4
     match (=) failed
     code:  assert {_output, 0} = System.cmd("bash", ["-c", "mix test 1>&2"], cd: "test_projects/example")
     left:  {_output, 0}
     right: {"", 1}
     stacktrace:
       test/bundlex/integration_test.exs:5: (test)
```

### PR DESCRIPTION
**Pull request by mickel8**
fix #70

### CODE REVIEW

File: test_projects/example/c_src/example/example_cnode.c [hunk 1]
```diff
@@ -130,7 +137,13 @@ int main(int argc, char **argv) {
...
   assert(ei_fd != ERL_ERROR);
 
-  int res = receive(ei_fd, node_name);
+  int res;
+  while(1) {
+    res = receive(ei_fd, node_name);
+    if(res != 0) {
+      break;
+    }
+  }
```
Comment (mat-hek) [inline test_projects/example/c_src/example/example_cnode.c:146]: This way we're going to repeat no matter which error happens. I think it's enough to stick to a single call to receive
